### ISSUE TITLE
JSON podatki

### ISSUE THREAD

**Issue by joahim** [overlordtm/COVID19.si#4]
Živjo! Bi bilo možno, da podatke pripraviš še v JSON obliki (seznam dnevnih recodov)? Uporabil bi jih za: https://joahim.github.io/covid-19/ Trenutno podatke jzbiram sam ampak vidim, da so tvoji bolj kakovostni in popolni. Če ne moreš, lahko tudi jaz pripravim PR.

**Comment by overlordtm** [comment]
Lahko en sample, v kaki obliki bi zelel? Ce prav razumem, en file za en dan?

**Comment by joahim** [comment]
Idealno bi bilo v podobni obliki kot https://github.com/joahim/covid-19/blob/master/COVID-19-SI.json

**Comment by joahim** [comment]
In če lahko, lepo prosim za vse fielde, ki ji imaš v CSV. Bom razširil grafe, da bodo kazali vse podatke.

**Comment by overlordtm** [comment]
Verjetno enkrat danes do vecera :)

**Comment by overlordtm** [comment]
Ti tole pomaga? https://covid19.rthand.com/api/data

Also, tale repo se bo zaprl, vse se seli na https://github.com/slo-covid-19

**Comment by joahim** [comment]
Top. Hvala!

**Comment by joahim** [comment]
Lahko prosim na server dodaš še `Access-Control-Allow-Origin: *`? Da bo lažje pobirat podatke iz single-page aplikacij.

**Comment by overlordtm** [comment]
Hmm, tistega serverja z linka ne upravljam jaz, ampak.nekdo iz slacka. Lahko se nam pa pridruzis na slacku slo-covid-19.slack.com pa se tam organiziramo.
